#!/usr/bin/env bash
# Create/reuse Telegram supergroup for pain alerts, write local overlay, sync VPS.
#
# Usage:
#   make setup-telegram-alert-group          # local telethon session
#   make setup-telegram-alert-group-vps      # VPS telethon session (recommended)
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VPS_MODE=0
if [[ "${1:-}" == "--vps" ]]; then
	VPS_MODE=1
fi

# shellcheck disable=SC1091
source "$ROOT/scripts/lib/vps_ssh.sh"

if [[ ! -f "$ROOT/.env" ]]; then
	printf 'setup-telegram-alert-group: missing .env\n' >&2
	exit 1
fi

set -a
# shellcheck disable=SC1091
source "$ROOT/.env"
set +a

alert_token="${TELEGRAM_ALERT_BOT_TOKEN:-${CRM_TELEGRAM_BOT_TOKEN:-${CRM_BOT_TOKEN:-}}}"
if [[ -z "$alert_token" ]]; then
	printf 'setup-telegram-alert-group: set CRM_BOT_TOKEN or TELEGRAM_ALERT_BOT_TOKEN in .env\n' >&2
	exit 1
fi

bot_username="${TELEGRAM_ALERT_BOT_USERNAME:-LeadProceesorBot}"

run_setup_py() {
	local runner="$1"
	$runner python3 /app/sources/telegram/setup_alert_group.py
}

if [[ "$VPS_MODE" == 1 ]]; then
	vps_load_config "$ROOT"
	if ! vps_ssh_require "$ROOT"; then
		exit 1
	fi
	vps_rsync_push "$ROOT"
	vps_post_sync_fix
	out="$(vps_ssh "set -euo pipefail; cd '${VPS_REMOTE_DIR}'
		docker compose -f docker-compose.telegram-realtime.yaml stop parser-telegram-realtime 2>/dev/null || true
		sleep 2
		docker compose build parser
		docker compose run --rm --no-deps \
			-e TELEGRAM_ALERT_BOT_USERNAME='${bot_username}' \
			--entrypoint sh parser -c \
			'cd /app && python3 sources/telegram/setup_alert_group.py'
	")"
else
	if [[ ! -f "$ROOT/data/runtime/telethon.session" ]]; then
		printf 'setup-telegram-alert-group: no local session; use: make setup-telegram-alert-group-vps\n' >&2
		exit 1
	fi
	out="$(cd "$ROOT" && PYTHONPATH=. TELEGRAM_ALERT_BOT_USERNAME="$bot_username" python3 sources/telegram/setup_alert_group.py)"
fi

group_id="$(printf '%s\n' "$out" | sed -n 's/^TELEGRAM_ALERT_CHANNEL=//p' | tail -1)"
if [[ -z "$group_id" ]]; then
	printf 'setup-telegram-alert-group: failed to resolve group id\n%s\n' "$out" >&2
	exit 1
fi

overlay="$ROOT/config/env/.env.telegram-alert.local"
cat >"$overlay" <<EOF
# Pain alerts -> private supergroup (not channel). Generated by setup-telegram-alert-group.sh
TELEGRAM_ALERT_ENABLED=1
TELEGRAM_ALERT_BOT_TOKEN=${alert_token}
TELEGRAM_ALERT_CHANNEL=${group_id}
EOF
chmod 600 "$overlay"

printf 'setup-telegram-alert-group: wrote %s (channel=%s)\n' "$overlay" "$group_id"

# Test Bot API delivery
test_resp="$(curl -s -X POST "https://api.telegram.org/bot${alert_token}/sendMessage" \
	-d "chat_id=${group_id}" \
	-d "text=BidShard pain alert group ready")"
if ! printf '%s' "$test_resp" | grep -q '"ok":true'; then
	printf 'setup-telegram-alert-group: sendMessage test failed: %s\n' "$test_resp" >&2
	exit 1
fi
printf 'setup-telegram-alert-group: sendMessage test ok\n'

if [[ "$VPS_MODE" == 1 ]]; then
	bash "$ROOT/scripts/ops/vps-sync-telegram-secrets.sh"
	vps_ssh "set -euo pipefail; cd '${VPS_REMOTE_DIR}'
		docker compose -f docker-compose.telegram-realtime.yaml restart parser-telegram-realtime
		docker compose -f docker-compose.telegram-realtime.yaml logs parser-telegram-realtime --tail 3
	"
fi

printf 'setup-telegram-alert-group: done\n'
